version: "3"

services:

  runtime-setup:
    image: swift-nio:16.04-5.1
    build:
      args:
        ubuntu_version: "xenial"
        swift_version: "5.1"

  test:
    image: swift-nio:16.04-5.1

  shell:
    image: swift-nio:16.04-5.1
